name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia a la rama principal de tu proyecto si es diferente
    paths:
      - 'docs/**'  # Si tus archivos de documentación están en una carpeta específica, ajústalo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatch git-cliff

      - name: Install dependencies
        run: hatch run sphinx:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html  # Ajusta al directorio donde se genera tu documentación
          publish_branch: gh-pages  # La rama donde se publicará, por defecto es gh-pages